### ISSUE TITLE
Bug: servername(s) on new lines: "list index out of range"

### ISSUE THREAD

**Issue by LukeShirnia** [luke7858/python-not-production-#2]
Head of serverblock:
```
server {
    listen 80;
    server_name
randomwebsite.com
www.randomwebsite.com;
```

Valid syntax: yes
```
# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

Script error:
```
Traceback (most recent call last):
  File "magento_info.py", line 852, in <module>
    main()
  File "magento_info.py", line 840, in main
    site_dict = n.select_option()
  File "magento_info.py", line 752, in select_option
    vhosts = self.get_vhosts()
  File "magento_info.py", line 666, in get_vhosts
    vhosts_list = self._get_vhosts()
  File "magento_info.py", line 510, in _get_vhosts
    ret += self._get_vhosts_info(f)
  File "magento_info.py", line 635, in _get_vhosts_info
    if l.split()[1] == "_":
IndexError: list index out of range
```

**Comment by LukeShirnia** [comment]
Resolved in https://github.com/LukeShirnia/magento_information/commit/acce6839028b09238ee40276b672393f8c559af9
